config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :employees
  get 'users/profile'
  get "users" => "users", as: "users"
  get 'users/show'
  # get 'users/edit'
  get "users/:id/edit" => "users#edit", as: "edit_user"
  put "users/:id/update" => "users#update", as: "update"

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'omni_auth'
  }
  devise_scope :user do
    get 'sign_in', to: 'users/sessions#new'
    get 'sign_up', to: 'users/registrations#new'
    get '/users/sign_out' => 'devise/sessions#destroy'

    get 'forgot_password', to: 'users/passwords#new'
    get 'reset_password', to: 'users/passwords#edit'
  end

  root to: 'application#home'
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord

     enum role: [:admin, :customer]

     mount_uploader :avatar, AvatarUploader

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:github]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
    end
  end

  # validates_integrity_of  :avatar
   validates_processing_of :avatar
 
  private
    def avatar_size_validation
      errors[:avatar] << "should be less than 500KB" if avatar.size > 0.5.megabytes
    end


end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def home;
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up)
    devise_parameter_sanitizer.permit(:account_update)
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:name)
    end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(_resource)
    root_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  private

  def sign_up_params
    params.require(:user).permit(:name, :avatar, :email, :password, :password_confirmation, :address_line, :land_mark, :street, :city,:state, :pincode, :role, :phone_number)
  end

  def account_update_params
    params.require(:user).permit(:name, :avatar, :email, :password, :password_confirmation, :current_password,:address_line, :land_mark, :street, :city,:state, :pincode, :role, :phone_number)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(account_update_params)
            redirect_to root_url
        else
            render 'edit'
        end
  end

  def users
    @users = User.all
  end

  def show
  end
   private

  def account_update_params
    params.require(:user).permit(:name, :avatar, :email, :password, :password_confirmation, :current_password,:address_line, :land_mark, :street, :city,:state, :pincode, :role, :phone_number)
  end

end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/home.html.erb
<section class="text-center m-5">
    <h1 class="text-center" >Profile</h1>
    <h1>
    <%= link_to "Users", users_path %></h1>
    
    <p>
      <strong>Email:</strong>
        <h5><%= current_user.email %></h5>
    </p>

    <div class="panel panel-default">
     <div class="panel-body">
        <%= image_tag current_user.avatar.small.url%>
     </div>     
     <div class="panel-body">
        <%= current_user.address_line%>
     </div>     
    <p>
      <strong>Name:</strong>
      <%= current_user.name %>
    </p>

    <p>
      <strong>Phone Number:</strong>
      <%= current_user.phone_number %>
    </p>

    <p>
      <strong>Address Line:</strong>
      <%= current_user.address_line %>
    </p>

    <p>
      <strong>Landmark:</strong>
      <%= current_user.land_mark %>
    </p>

    <p>
      <strong>Street:</strong>
      <%= current_user.street %>
    </p>

    <p>
      <strong>City:</strong>
      <%= current_user.city %>
    </p>

    <p>
      <strong>State:</strong>
      <%= current_user.state %>
    </p>

   <p>
      <strong>Pincode:</strong>
      <%= current_user.pincode %>
    </p>

   <p>
      <strong>Role:</strong>
      <%= current_user.role %>
    </p>
   
    </div>  

    <%= link_to "Edit", edit_user_path(current_user) %>
    <%=
        link_to_if(current_user.nil?, "Login", sign_in_path, class: 'btn btn-primary m-5') do
            link_to('Sign out',  destroy_user_session_path, :method => 'delete', class: 'btn btn-danger m-5')
        end
    %>

</section>

app/views/employees/_form.html.erb
<%= form_with(model: employee, local: true) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
        <% employee.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Employees</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.name %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @employee.name %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Rails 6 Devise Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<h2>Edit </h2>

<%= form_for(@user, url: update_path(@user), html: { method: :put }) do |f| %>
<% if current_user.role == 'admin' %>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </div>
<% end %>

<% if @user.role != 'admin' %>

 <div class="field">
  <%= f.label :roles %><br>
  <%= f.select :role, User.roles.keys.map { |w| [w.humanize, w] } %>
 </div>
  <div class="field">
    <%= f.label :address_line %><br>
    <%= f.text_field :address_line %>
  </div>

    <div class="field">
    <%= f.label :street %><br>
    <%= f.text_field :street %>
  </div>

  <div class="field">
    <%= f.label :land_mark %><br>
    <%= f.text_field :land_mark %>
  </div>

  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>

  <div class="field">
    <%= f.label :pincode %><br>
    <%= f.text_field :pincode %>
  </div>
<% end %>
  <div class="field">
    <%= f.label :profile_picture %><br>
    <%= f.file_field :avatar %>
  </div>


  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

<%= link_to "Back", :back %>

app/views/users/profile.html.erb
<h1>Users#profile</h1>
<p>Find me in app/views/users/profile.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/users.html.erb
<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone Number</th>
      <th>Role</th>
      <th>Address Line</th>
      <th>Land Mark</th>
      <th>Street</th>
      <th>City</th>
      <th>State</th>
      <th>Pincode</th>
      <th>Profile</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.phone_number %></td>
        <td><%= user.role %></td>
        <td><%= user.address_line %></td>
        <td><%= user.land_mark %></td>
        <td><%= user.street %></td>
        <td><%= user.city %></td>
        <td><%= user.state %></td>
        <td><%= user.pincode %></td>
        <td><%= image_tag user.avatar.thumb.url%></td>
        <td><%= link_to 'Show', users_show_path(user) %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "Back", :back %>